// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO4h1kyCt777CQcycsnszc5MFL4xaodQE',
    appId: '1:285343917002:android:a88d88044ba87f67cb6533',
    messagingSenderId: '285343917002',
    projectId: 'filmmer',
    storageBucket: 'filmmer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8QcbFGM-tUE-dhyjj8UbyURs4fAtUhqQ',
    appId: '1:285343917002:ios:a8e2080ff86792d1cb6533',
    messagingSenderId: '285343917002',
    projectId: 'filmmer',
    storageBucket: 'filmmer.appspot.com',
    androidClientId: '285343917002-1ugmuuqkelo736fg4pein0ci6r2et65r.apps.googleusercontent.com',
    iosClientId: '285343917002-ge8aknma5879va75gbq6ioqa0ilojgc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmmerRewrite',
  );
}
